sudo: required
dist: trusty
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty
  sonarqube: # https://docs.travis-ci.com/user/sonarqube/
    organization: "jpmag" # the key of the org you chose at step #3
    token:
      secure: ZAoBOLpLHcOuXc4yJSmg1Y8ydrJlVCVRBWB8ajIzKoJ///akYBrRu8p3SFHi7H9BoHrbXN1Ta22dqPywtNQuwkDOMOtWijDgI8HJgmNeDXyXajchxKCA3BEfjpb8mh9qQzn7WaS4CLoYps2RUxFnBLsqJlDve6rsNVib+qBMq0GUWIiVnI26NWukFz2L+teMM+p4ZKSR/OUp2OydJO/ZJvcjlcxlpnOXqZ+p9k4ft9QFjZp16Oh1VOVdJsBgZGPtBmaX0iiynIc1beSLoewnwF+LvaEG0LDlRtHXwaUYtXFnWIpYab96VXrv0ub5iGhPi4AmvT9URTFHt52NVIP/myaxX02730A7/eJvTVatPka9UTy/vKY4JE+HM+kMd6U8MLjHb8ZzQKAWJl7zIgULS5O0XcANajfS3zBsNnt9co5N+fLvmr4ziAHPJrui2z0hCLaIa1zKAn7LXa7oFAqRxHaOUyfS9STjOYJdxRatIEo+wrl6FRN8Cr/8tMASbzL0kbJmn6qJWjSy5qn+zmQ31GmvJZtszj2I+FBGAVW0XqAndwGr9rgpEHXcu9v0r7xnRqlBB2ihIu/swDB/WT5CmS32K4n9WdC25XJljlUi6Xq9jl0ZF+Q/3KkNGX1w4IPzjTCEj/K3A4N8WhC/9uoViIMi4FGD33Xf60DJ1TsTASs=

# we're not using combination parameters here to ensure that the builds
# run in the order we want. (We want to perform the fastest tests first so
# failed tests appear as early as possible).
env:
  global:
    - PATH=/usr/local/bin:$PATH

# NOTE: The compiler setting is unused. It simply makes the display on
# travis-ci.org more readable.
# WARNING: do not use the name CXX. Travis will ignore the value here.
matrix:
  allow_failures:
    #
    # -------------------------------------------------------------------------
    - env: SONARQUBE=1 CXX_=g++-5 A=64
  include:
    #
    # QUICKTEST----------------------------------------------------------------
    # default version for gcc in trusty is 4.8; c4stl won't work with it.
    #
    - env: CXX_=g++-5       A=64 BT=Quicktest
    - env: CXX_=clang++-3.6 A=64 BT=Quicktest
    #
    - env: CXX_=g++-6       A=64 BT=QuicktestRelease
    - env: CXX_=clang++-3.9 A=64 BT=QuicktestRelease
    #
    - env: CXX_=g++-5       A=32 BT=Quicktest
    - env: CXX_=clang++-3.6 A=32 BT=Quicktest
    #
    - env: CXX_=g++-6       A=32 BT=QuicktestRelease
    - env: CXX_=clang++-3.9 A=32 BT=QuicktestRelease
    #
    - env: CXX_=g++-6       A=64 BT=Quicktest
    - env: CXX_=clang++-3.7 A=64 BT=Quicktest
    #
    - env: CXX_=g++-6       A=32 BT=Quicktest
    - env: CXX_=clang++-3.7 A=32 BT=Quicktest
    #
    - env: CXX_=g++-7       A=64 BT=Quicktest
    - env: CXX_=clang++-3.8 A=64 BT=Quicktest
    #
    - env: CXX_=g++-7       A=32 BT=Quicktest
    - env: CXX_=clang++-3.8 A=32 BT=Quicktest
    #
    - env: CXX_=clang++-3.9 A=64 BT=Quicktest
    - env: CXX_=clang++-3.9 A=32 BT=Quicktest
    #
    # ----------- clang with sanitizers (slower)
    #
    - env: CXX_=clang++-3.6 A=64 BT=Quicktest SAN=ALL VG=OFF
    - env: CXX_=clang++-3.6 A=32 BT=Quicktest SAN=ALL VG=OFF
    #
    - env: CXX_=clang++-3.7 A=64 BT=Quicktest SAN=ALL VG=OFF
    - env: CXX_=clang++-3.7 A=32 BT=Quicktest SAN=ALL VG=OFF
    #
    - env: CXX_=clang++-3.8 A=64 BT=Quicktest SAN=ALL VG=OFF
    - env: CXX_=clang++-3.8 A=32 BT=Quicktest SAN=ALL VG=OFF
    #
    - env: CXX_=clang++-3.9 A=64 BT=Quicktest SAN=ALL VG=OFF
    - env: CXX_=clang++-3.9 A=32 BT=Quicktest SAN=ALL VG=OFF
    #
    # ----------- Coverage (covers all tests, slow) -------------------------
    #
    #- env: CXX_=g++-6 A=64 BT=Coverage
    #
    # DEBUG----------------------------------------------------------------
    # ----------- Debug (covers all tests, slow)
    # valgrind is switched off to prevent exceeding the max travis time
    #
    - env: CXX_=g++-6 A=64 BT=Debug VG=OFF
    - env: CXX_=g++-6 A=32 BT=Debug VG=OFF
    #
    - env: CXX_=clang++-3.9 A=64 BT=Debug
    - env: CXX_=clang++-3.9 A=32 BT=Debug
    #
    # RELEASE----------------------------------------------------------------
    # ----------- Release (covers all tests, slow)
    # too slow, unfortunately.
    #- env: CXX_=g++-6 A=64 BT=Release
    #- env: CXX_=g++-6 A=32 BT=Release
    #
    #- env: CXX_=clang++-3.7 A=64 BT=Release
    #- env: CXX_=clang++-3.7 A=32 BT=Release
    #
    # ----------- Full sanitize (covers all type combination in the tests, VERY slow) ---------------
    # the sanitizers are run one at a time to prevent exceeding the max travis time
    #
    - env: CXX_=clang++-3.9 A=64 BT=Debug SAN=A VG=OFF
    - env: CXX_=clang++-3.9 A=32 BT=Debug SAN=A VG=OFF
    #
    - env: CXX_=clang++-3.9 A=64 BT=Debug SAN=T VG=OFF
    - env: CXX_=clang++-3.9 A=32 BT=Debug SAN=T VG=OFF
    #
    - env: CXX_=clang++-3.9 A=64 BT=Debug SAN=M VG=OFF
    - env: CXX_=clang++-3.9 A=32 BT=Debug SAN=M VG=OFF
    #
    - env: CXX_=clang++-3.9 A=64 BT=Debug SAN=UB VG=OFF
    - env: CXX_=clang++-3.9 A=32 BT=Debug SAN=UB VG=OFF

install:
  - bash -x .ci/travis-install.sh

script:
  - bash -x .ci/travis-test.sh

after_success:
  - echo "Success!"
  #- if [ "${BT}" == "Coverage" -a "${TRAVIS_OS_NAME}" == "linux" ]; then
  #    coveralls --include src --include include --gcov-options '\-lp' --root .. --build-root .;
  #  fi
