sudo: required
dist: trusty
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty

env:
  global:
    - PATH=/usr/local/bin:$PATH
    - PEDANTIC=ON

# NOTE: The compiler setting is unused. It simply makes the display on
# travis-ci.org more readable.
matrix:
  include:
    # QUICKTEST----------------------------------------------------------------
    # default version for gcc in trusty is 4.8; c4stl won't work with it.
    - compiler: gcc
      env: COMPILER=g++-5 BUILD_TYPE=Quicktest
    - compiler: gcc
      env: COMPILER=g++-5 EXTRA_FLAGS="-m32" BUILD_TYPE=Quicktest
    #
    #
    - compiler: gcc
      env: COMPILER=g++-6 BUILD_TYPE=Quicktest DPKG="g++-6"
    - compiler: gcc
      env: COMPILER=g++-6 EXTRA_FLAGS="-m32" BUILD_TYPE=Quicktest DPKG="g++-6-multilib"
    #
    #
    - compiler: clang
      env: COMPILER=clang++-3.7 BUILD_TYPE=Quicktest DPKG="clang-3.7"
    - compiler: clang
      env: COMPILER=clang++-3.7 EXTRA_FLAGS="-m32" BUILD_TYPE=Quicktest DPKG="clang-3.7"
    #
    #
    - compiler: clang
      env: COMPILER=clang++-3.8 BUILD_TYPE=Quicktest DPKG="clang-3.8"
    - compiler: clang
      env: COMPILER=clang++-3.8 EXTRA_FLAGS="-m32" BUILD_TYPE=Quicktest DPKG="clang-3.8"
    #
    #
    - compiler: clang
      env: COMPILER=clang++-3.9 BUILD_TYPE=Quicktest DPKG="clang-3.9"
    - compiler: clang
      env: COMPILER=clang++-3.9 EXTRA_FLAGS="-m32" BUILD_TYPE=Quicktest DPKG="clang-3.9"

#before_script:
#  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
#  - sudo apt-get update
#  - sudo apt-get -y install cmake

install:
  - bash -x .ci/travis-install.sh

script:
  - bash -x .ci/travis-test.sh

after_success:
  - echo "Success!"
  #- if [ "${BUILD_TYPE}" == "Coverage" -a "${TRAVIS_OS_NAME}" == "linux" ]; then
  #    coveralls --include src --include include --gcov-options '\-lp' --root .. --build-root .;
  #  fi
