sudo: required
dist: trusty
language: cpp

env:
  global:
    - /usr/local/bin:$PATH

# NOTE: The compiler setting is unused. It simply makes the display on
# travis-ci.org more readable.
matrix:
    include:
        # QUICKTEST----------------------------------------------------------------
        # default version for gcc in trusty is 4.8; c4stl won't work with it.
        - compiler: gcc5
          addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
              packages:
                - g++-5
          env: COMPILER=g++-5 C_COMPILER=gcc-5 BUILD_TYPE=Quicktest
        - compiler: gcc5-32
          addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
              packages:
                - g++-5
                - g++-multilib
          env: COMPILER=g++-5 C_COMPILER=gcc-5 BUILD_TYPE=Quicktest EXTRA_FLAGS="-m32"
###         #
###         #
###         - compiler: clang3.5
###           env: COMPILER=clang++ C_COMPILER=clang BUILD_TYPE=Quicktest
###         - compiler: clang3.5-32
###           addons:
###             apt:
###               packages:
###                 - g++-multilib
###          env: COMPILER=clang++ C_COMPILER=clang BUILD_TYPE=Quicktest EXTRA_FLAGS="-m32"
###         #
###         #
###         - compiler: gcc6
###           addons:
###             apt:
###               sources:
###                 - ubuntu-toolchain-r-test
###               packages:
###                 - g++-6
###           env:
###             - COMPILER=g++-6 C_COMPILER=gcc-6  BUILD_TYPE=Quicktest
###         - compiler: gcc6-32
###           addons:
###             apt:
###               sources:
###                 - ubuntu-toolchain-r-test
###               packages:
###                 - g++-multilib
###                 - g++-6
###           env:
###             - COMPILER=g++-6 C_COMPILER=gcc-6  BUILD_TYPE=Quicktest EXTRA_FLAGS="-m32"
###         #
###         #
###         - compiler: clang3.8
###           addons:
###             apt:
###               packages:
###                 - clang-3.8
###           env: COMPILER=clang++-3.8 C_COMPILER=clang-3.8 BUILD_TYPE=QuickTest
###         - compiler: clang3.8-32
###           addons:
###             apt:
###               packages:
###                 - clang-3.8
###                 - g++-multilib
###           env: COMPILER=clang++-3.8 C_COMPILER=clang-3.8 BUILD_TYPE=QuickTest EXTRA_FLAGS="-m32"
###         ##
###         ##
###         #- compiler: clang3.9
###         #  addons:
###         #    apt:
###         #      sources:
###         #        - llvm-toolchain-precise-3.9
###         #      packages:
###         #        - clang-3.9
###         #  env: COMPILER=clang++-3.9 C_COMPILER=clang-3.9 BUILD_TYPE=QuickTest
###         #- compiler: clang3.9-32
###         #  addons:
###         #    apt:
###         #      sources:
###         #        - llvm-toolchain-precise-3.9
###         #      packages:
###         #        - clang-3.9
###         #        - g++-multilib
###         #  env: COMPILER=clang++-3.9 C_COMPILER=clang-3.9 BUILD_TYPE=QuickTest EXTRA_FLAGS="-m32"
###         ##
###         ##
###         #- compiler: clang4.0
###         #  addons:
###         #    apt:
###         #      sources:
###         #        - llvm-toolchain-precise-4.0
###         #      packages:
###         #        - clang-4.0
###         #  env: COMPILER=clang++-4.0 C_COMPILER=clang-4.0 BUILD_TYPE=QuickTest
###         #- compiler: clang4.0-32
###         #  addons:
###         #    apt:
###         #      sources:
###         #        - llvm-toolchain-precise-4.0
###         #      packages:
###         #        - clang-4.0
###         #        - g++-multilib
###         #  env: COMPILER=clang++-4.0 C_COMPILER=clang-4.0 BUILD_TYPE=QuickTest EXTRA_FLAGS="-m32"
###         #
###         # DEBUG----------------------------------------------------------------
###         # debug builds of the tests are slow to build, so there's less testing.
###         - compiler: gcc5
###           addons:
###             apt:
###               sources:
###                 - ubuntu-toolchain-r-test
###               packages:
###                 - g++-5
###           env: COMPILER=g++-5 C_COMPILER=gcc-5 BUILD_TYPE=Debug
###         - compiler: gcc5-32
###           addons:
###             apt:
###               sources:
###                 - ubuntu-toolchain-r-test
###               packages:
###                 - g++-5
###                 - g++-multilib
###           env: COMPILER=g++-5 C_COMPILER=gcc-5 BUILD_TYPE=Debug EXTRA_FLAGS="-m32"
###         #
###         #
###         - compiler: clang3.8
###           addons:
###             apt:
###               packages:
###                 - clang-3.8
###           env: COMPILER=clang++-3.8 C_COMPILER=clang-3.8 BUILD_TYPE=Debug
###         - compiler: clang3.8-32
###           addons:
###             apt:
###               packages:
###                 - clang-3.8
###                 - g++-multilib
###           env: COMPILER=clang++-3.8 C_COMPILER=clang-3.8 BUILD_TYPE=Debug EXTRA_FLAGS="-m32"
###         #
###         # RELEASE----------------------------------------------------------------
###         # debug builds of the tests are slow to build, so there's less testing.
###         - compiler: gcc5
###           addons:
###             apt:
###               sources:
###                 - ubuntu-toolchain-r-test
###               packages:
###                 - g++-5
###           env: COMPILER=g++-5 C_COMPILER=gcc-5 BUILD_TYPE=Debug
###         - compiler: gcc5-32
###           addons:
###             apt:
###               sources:
###                 - ubuntu-toolchain-r-test
###               packages:
###                 - g++-5
###                 - g++-multilib
###           env: COMPILER=g++-5 C_COMPILER=gcc-5 BUILD_TYPE=Debug EXTRA_FLAGS="-m32"
###         #
###         #
###         - compiler: clang3.8
###           addons:
###             apt:
###               packages:
###                 - clang-3.8
###           env: COMPILER=clang++-3.8 C_COMPILER=clang-3.8 BUILD_TYPE=Debug
###         - compiler: clang3.8-32
###           addons:
###             apt:
###               packages:
###                 - clang-3.8
###                 - g++-multilib
###           env: COMPILER=clang++-3.8 C_COMPILER=clang-3.8 BUILD_TYPE=Debug EXTRA_FLAGS="-m32"
###         #
###         # COVERAGE----------------------------------------------------------------
###         - compiler: gcc5
###           addons:
###             apt:
###               sources:
###                 - ubuntu-toolchain-r-test
###               packages:
###                 - g++-5
###           env: COMPILER=g++-5 C_COMPILER=gcc-5 BUILD_TYPE=Coverage
### 

#before_script:
#  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
#  - sudo apt-get update
#  - sudo apt-get -y install cmake

install:
  - $COMPILER --version
  - if [ "${BUILD_TYPE}" == "Coverage" -a "${TRAVIS_OS_NAME}" == "linux" ]; then
      PATH=~/.local/bin:${PATH};
      pip install --user --upgrade pip;
      pip install --user cpp-coveralls;
    fi
  - export cmkargs="-DCMAKE_C_COMPILER=${C_COMPILER} -DCMAKE_CXX_COMPILER=${COMPILER}"
  # compile and install external libraries
  - mkdir -p build/extern_build && cd build/extern_build
  - pwd
  - echo $cmkargs
  - cmake ${cmkargs} -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="${EXTRA_FLAGS}" -DCMAKE_INSTALL_PREFIX=`pwd`/../extern_install ../../extern
  - cmake --build . --config Release
  - cd -

script:
  - echo $cmkargs
  - cd build
  - pwd
  - cmake $cmkargs -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_FLAGS="${EXTRA_FLAGS}" -DC4STL_EXTERN_DIR=`pwd`/extern_install ..
  - make CTEST_OUTPUT_ON_FAILURE=1 c4stl-test

after_success:
  - echo "Success!"
  #- if [ "${BUILD_TYPE}" == "Coverage" -a "${TRAVIS_OS_NAME}" == "linux" ]; then
  #    coveralls --include src --include include --gcov-options '\-lp' --root .. --build-root .;
  #  fi
