version: '{build}'

image: Visual Studio 2017

environment:
  matrix:
    - compiler: msvc-15-seh
      generator: "Visual Studio 15 2017"
      configuration: Quicktest
      externconfig: Debug

    - compiler: msvc-15-seh
      generator: "Visual Studio 15 2017 Win64"
      configuration: Quicktest
      externconfig: Debug

    - compiler: msvc-14-seh
      generator: "Visual Studio 14 2015"
      configuration: Quicktest
      externconfig: Debug

    - compiler: msvc-14-seh
      generator: "Visual Studio 14 2015 Win64"
      configuration: Quicktest
      externconfig: Debug

    - compiler: msvc-12-seh
      generator: "Visual Studio 12 2013"
      configuration: Quicktest
      externconfig: Debug

    - compiler: msvc-12-seh
      generator: "Visual Studio 12 2013 Win64"
      configuration: Quicktest
      externconfig: Debug

    #- compiler: gcc-5.3.0-posix
    #  generator: "MinGW Makefiles"
    #  cxx_path: 'C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin'
    #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    #  configuration: Quicktest
    #  externconfig: Debug

    #------------------------------------------------------------------------------
    - compiler: msvc-15-seh
      generator: "Visual Studio 15 2017"
      configuration: Debug
      externconfig: Debug

    - compiler: msvc-15-seh
      generator: "Visual Studio 15 2017 Win64"
      configuration: Debug
      externconfig: Debug

    - compiler: msvc-14-seh
      generator: "Visual Studio 14 2015"
      configuration: Debug
      externconfig: Debug

    - compiler: msvc-14-seh
      generator: "Visual Studio 14 2015 Win64"
      configuration: Debug
      externconfig: Debug

    - compiler: msvc-12-seh
      generator: "Visual Studio 12 2013"
      configuration: Debug
      externconfig: Debug

    - compiler: msvc-12-seh
      generator: "Visual Studio 12 2013 Win64"
      configuration: Debug
      externconfig: Debug

    #- compiler: gcc-5.3.0-posix
    #  generator: "MinGW Makefiles"
    #  cxx_path: 'C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin'
    #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    #  configuration: Debug
    #  externconfig: Debug

    #------------------------------------------------------------------------------
    - compiler: msvc-15-seh
      generator: "Visual Studio 15 2017"
      configuration: Release
      externconfig: Release

    - compiler: msvc-15-seh
      generator: "Visual Studio 15 2017 Win64"
      configuration: Release
      externconfig: Release

    - compiler: msvc-14-seh
      generator: "Visual Studio 14 2015"
      configuration: Release
      externconfig: Release

    - compiler: msvc-14-seh
      generator: "Visual Studio 14 2015 Win64"
      configuration: Release
      externconfig: Release

    - compiler: msvc-12-seh
      generator: "Visual Studio 12 2013"
      configuration: Release
      externconfig: Release

    - compiler: msvc-12-seh
      generator: "Visual Studio 12 2013 Win64"
      configuration: Release
      externconfig: Release

    #- compiler: gcc-5.3.0-posix
    #  generator: "MinGW Makefiles"
    #  cxx_path: 'C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin'
    #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    #  configuration: Release
    #  externconfig: Release

matrix:
  fast_finish: true

install:
  - git submodule update --init --recursive
  # git bash conflicts with MinGW makefiles
  - if "%generator%"=="MinGW Makefiles" (set "PATH=%PATH:C:\Program Files\Git\usr\bin;=%")
  - if not "%cxx_path%"=="" (set "PATH=%PATH%;%cxx_path%")

build_script:
  - md _build -Force
  - cd _build
  - md _extern_build -Force
  - cd _extern_build
  - echo %externconfig%
  - cmake -G "%generator%" "-DCMAKE_BUILD_TYPE=%externconfig%" "-DCMAKE_INSTALL_PREFIX=../_extern_install" ../../extern
  - cmake --build . --config %externconfig%
  - cd ..

test_script:
  - echo %configuration%
  - cmake -G "%generator%" "-DCMAKE_BUILD_TYPE=%configuration%" "-DC4STL_EXTERN_DIR=_extern_install" ..
  - dir
  - dir test
  - cmake --build . --config %configuration% --target test/c4stl-test
  #- ctest -c %configuration% --timeout 300 --output-on-failure

artifacts:
  - path: '_build/CMakeFiles/*.log'
    name: logs
  - path: '_build/Testing/**/*.xml'
    name: test_results

skip_commits:
  files:
    - .gitignore
    - .travis*
    - .ci/travis*
    - .ci/dev_*
    - .ci/show_*
    - doc/*
    - LICENSE.txt
    - README.*
